# Generated by Django 2.1.5 on 2019-01-16 01:56

from django.db import migrations, models
import webview.utils.upyun_storage


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0003_staticfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfile',
            name='url',
            field=models.FileField(storage=webview.utils.upyun_storage.UpyunStorage(), upload_to='static/%Y/%m/%d/'),
        ),
    ]
